[package]
name = "heretek-model"
description = "Heretek model crate"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
heretek-core = { version = "0.0.1", path = "../heretek-core" }
reqwest = { version = "0.13.5", features = ["blocking", "json"] }
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
